#!/usr/bin/env node
// Codegen (docs/design/08 §6; D-028): emits C# constants/enums into Unity/Assets/Game/Generated from
// Tools/codegen.config.json and content files. Idempotent. CI runs `--check` (CodegenClean).
//
//   node Tools/codegen.mjs          write
//   node Tools/codegen.mjs --check  fail if the committed generated files differ
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CONFIG = JSON.parse(readFileSync(join(ROOT, 'Tools', 'codegen.config.json'), 'utf8'));
// Fragments (Tools/codegen.d/*.json) let parallel streams own their key sets without editing one shared file.
const FRAGMENTS = join(ROOT, 'Tools', 'codegen.d');
if (existsSync(FRAGMENTS)) {
  for (const f of readdirSync(FRAGMENTS).filter(f => f.endsWith('.json')).sort()) {
    const frag = JSON.parse(readFileSync(join(FRAGMENTS, f), 'utf8'));
    for (const key of ['enums', 'keySets', 'numberSets', 'stringTables']) if (frag[key]) CONFIG[key] = [...(CONFIG[key] || []), ...frag[key]];
  }
}
const CONTENT = join(ROOT, 'Unity', 'Assets', 'StreamingAssets', 'Content');
const OUT = join(ROOT, CONFIG.outDir);
const CHECK = process.argv.includes('--check');
const HEADER = '// <auto-generated> by Tools/codegen.mjs from Tools/codegen.config.json and content. Do not edit. </auto-generated>\n';

const pascal = (s) => s.replace(/(^|[^A-Za-z0-9]+)([A-Za-z0-9])/g, (_, __, c) => c.toUpperCase()).replace(/^[0-9]/, (d) => `_${d}`);
const esc = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t');
const doc = (text, indent = '    ') => `${indent}/// <summary>${text.replace(/&/g, '&amp;').replace(/</g, '&lt;')}</summary>\n`;

function uniqueNames(pairs) {
  const seen = new Set();
  for (const [name] of pairs) { if (seen.has(name)) throw new Error(`codegen: duplicate identifier ${name}`); seen.add(name); }
  return pairs;
}
function keySet(name, docText, entries) {
  const lines = [HEADER, `namespace ${CONFIG.namespace}\n{\n`, doc(docText, '    '), `    public static class ${name}\n    {\n`];
  for (const [id, value] of uniqueNames(entries)) lines.push(`        public const string ${id} = "${esc(value)}";\n`);
  lines.push('    }\n}\n');
  return lines.join('');
}
function enumFile(name, docText, values) {
  const pairs = uniqueNames(values.map(v => [pascal(v), v]));
  const lines = [HEADER, `namespace ${CONFIG.namespace}\n{\n`, doc(docText), `    public enum ${name}\n    {\n        None = 0,\n`];
  pairs.forEach(([id], i) => lines.push(`        ${id} = ${i + 1},\n`));
  lines.push('    }\n\n', doc(`Wire names for ${name} (the strings used in content).`), `    public static class ${name}Names\n    {\n`);
  lines.push(`        public static readonly string[] All = new string[]\n        {\n${pairs.map(([, v]) => `            "${esc(v)}",`).join('\n')}\n        };\n\n`);
  lines.push(`        public static ${name} Parse(string wire)\n        {\n            switch (wire)\n            {\n`);
  for (const [id, v] of pairs) lines.push(`                case "${esc(v)}": return ${name}.${id};\n`);
  lines.push(`                default: return ${name}.None;\n            }\n        }\n\n`);
  lines.push(`        public static string ToWire(${name} value)\n        {\n            switch (value)\n            {\n`);
  for (const [id, v] of pairs) lines.push(`                case ${name}.${id}: return "${esc(v)}";\n`);
  lines.push('                default: return null;\n            }\n        }\n    }\n}\n');
  return lines.join('');
}

const files = {};
for (const e of CONFIG.enums) {
  const data = JSON.parse(readFileSync(join(CONTENT, e.from), 'utf8'));
  files[`${e.name}.g.cs`] = enumFile(e.name, e.doc, e.path.split('.').reduce((o, k) => o[k], data));
}
for (const k of CONFIG.keySets) files[`${k.name}.g.cs`] = keySet(k.name, k.doc, Object.entries(k.keys));
for (const n of CONFIG.numberSets || []) {
  const lines = [HEADER, `namespace ${CONFIG.namespace}\n{\n`, doc(n.doc), `    public static class ${n.name}\n    {\n`];
  for (const [id, v] of uniqueNames(Object.entries(n.values))) lines.push(`        public const ${n.type} ${id} = ${v};\n`);
  lines.push('    }\n}\n');
  files[`${n.name}.g.cs`] = lines.join('');
}
for (const t of CONFIG.stringTables || []) {
  const table = JSON.parse(readFileSync(join(CONTENT, t.from), 'utf8'));
  files[`${t.name}.g.cs`] = keySet(t.name, t.doc, Object.keys(table).sort().map(k => [pascal(k), k]));
}
const manifest = JSON.parse(readFileSync(join(CONTENT, 'manifest.json'), 'utf8'));
const contentEntries = Object.keys(manifest.files).sort().map(p => [pascal(p.replace(/\.json$/, '')), p]);
files[`${CONFIG.contentFiles.name}.g.cs`] = keySet(CONFIG.contentFiles.name, CONFIG.contentFiles.doc, contentEntries);

if (CHECK) {
  const drift = Object.entries(files).filter(([f, text]) => !existsSync(join(OUT, f)) || readFileSync(join(OUT, f), 'utf8').replace(/\r\n/g, '\n') !== text).map(([f]) => f);
  const stale = existsSync(OUT) ? readdirSync(OUT).filter(f => f.endsWith('.g.cs') && !(f in files)) : [];
  if (drift.length || stale.length) { console.error(`codegen: generated code is stale — run node Tools/codegen.mjs\n  ${[...drift, ...stale.map(s => `${s} (stale)`)].join('\n  ')}`); process.exit(1); }
  console.log(`codegen: check ok (${Object.keys(files).length} files)`);
} else {
  mkdirSync(OUT, { recursive: true });
  for (const f of readdirSync(OUT).filter(f => f.endsWith('.g.cs') && !(f in files))) rmSync(join(OUT, f));
  for (const [f, text] of Object.entries(files)) writeFileSync(join(OUT, f), text);
  console.log(`codegen: wrote ${Object.keys(files).length} files to ${CONFIG.outDir}`);
}
