#!/usr/bin/env node
// Regenerates Tools/codegen.d/map.json from the names the map port uses (US-4.2): keys are read off
// Ashen.Domain.Map (and the content factory) by their alias MK. and spelled as their camelCase wire names; closed
// values (MV.) and messages (MM.) come from Tools/map-keys/values.json and messages.json. A name CombatKeys or
// CombatValues already owns is refused: the map code must reuse K./V. rather than mint a duplicate.
//   node Tools/map-keys.mjs        (then node Tools/codegen.mjs)
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';

const DIRS = ['Unity/Assets/Game/Domain/Map'];
const FILES = ['Unity/Assets/Game/Content/Runtime/RuntimeRegistries.cs'];
const src = [
  ...DIRS.flatMap((dir) => readdirSync(dir).filter((f) => f.endsWith('.cs')).map((f) => `${dir}/${f}`)),
  ...FILES,
].map((f) => readFileSync(f, 'utf8')).join('\n');
const used = (alias) => [...new Set([...src.matchAll(new RegExp(`(?<![A-Za-z0-9_.])${alias}[.]([A-Z][A-Za-z0-9]*)`, 'g'))].map((m) => m[1]))].sort();
const camel = (s) => s[0].toLowerCase() + s.slice(1);
const combat = JSON.parse(readFileSync('Tools/codegen.d/combat.json', 'utf8'));
const owned = (name) => Object.keys(combat.keySets.find((k) => k.name === name).keys);

let failed = false;
const refuse = (what, names) => { if (names.length) { console.error(`map-keys: ${what}: ${names.join(', ')}`); failed = true; } };

const keys = used('MK');
refuse('already in CombatKeys (use K.)', keys.filter((k) => owned('CombatKeys').includes(k)));
const V = JSON.parse(readFileSync('Tools/map-keys/values.json', 'utf8'));
const values = used('MV');
refuse('already in CombatValues (use V.)', values.filter((k) => owned('CombatValues').includes(k)));
refuse('missing from Tools/map-keys/values.json', values.filter((k) => !(k in V)));
const M = JSON.parse(readFileSync('Tools/map-keys/messages.json', 'utf8'));
const messages = used('MM');
refuse('missing from Tools/map-keys/messages.json', messages.filter((k) => !(k in M)));
refuse('unused in values.json', Object.keys(V).filter((k) => !values.includes(k)));
refuse('unused in messages.json', Object.keys(M).filter((k) => !messages.includes(k)));
if (failed) process.exit(1);

const out = {
  comment: 'Map port names (us-4.2; the C# port of engine/mapgen.js, model/floorplan.js, engine/actmap.js). Regenerated by Tools/map-keys.mjs from the aliases MK./MV./MM. in Ashen.Domain.Map; names CombatKeys/CombatValues already own are reused, never duplicated.',
  keySets: [
    { name: 'MapKeys', doc: 'Keys of map graphs, map configs, run history rows, oracle table dumps and rules/mapEngine.json the map port reads (shipped wire names).', keys: Object.fromEntries(keys.map((k) => [k, camel(k)])) },
    { name: 'MapValues', doc: 'Closed map values: refusal key templates ({0} slots), separators and typeof names.', keys: Object.fromEntries(values.map((k) => [k, V[k]])) },
    { name: 'MapMessages', doc: 'Map port error messages (developer-facing; {0}.. are string.Format slots).', keys: Object.fromEntries(messages.map((k) => [k, M[k]])) },
  ],
  numberSets: [
    { name: 'MapNumbers', type: 'uint', doc: 'Arithmetic constants of the map rules (definitions, not tuning): the sweepSeed multiplier (Knuth) and the uint32 width for ToInt32.', values: { SweepMultiplier: '2654435761', Uint32Bits: '32' } },
  ],
};
writeFileSync('Tools/codegen.d/map.json', `${JSON.stringify(out, null, 2)}\n`);
console.log(Object.fromEntries(out.keySets.map((k) => [k.name, Object.keys(k.keys).length])));
