#!/usr/bin/env node
// UI tokens → USS (docs/design/08 §6, 09 §5.3). Generates Tokens.uss from ui/tokens.json and polices the
// hand-written USS: kit and screen style sheets may only use the generated variables for colours, lengths and
// durations (no hex/rgb colours, no numeric lengths other than 0, no numbers other than 0 and 1).
//
//   node Tools/ui-tokens.mjs          write Tokens.uss
//   node Tools/ui-tokens.mjs --check  fail if Tokens.uss is stale or a USS file uses a raw value
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync, mkdirSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS = join(ROOT, 'Unity', 'Assets', 'StreamingAssets', 'Content', 'ui', 'tokens.json');
const UI = join(ROOT, 'Unity', 'Assets', 'Game', 'Presentation', 'UI');
const OUT = join(UI, 'Resources', 'UI', 'Styles', 'Tokens.uss');
const CHECK = process.argv.includes('--check');

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

export function renderTokens(tokens) {
  const lines = ['/* <auto-generated> by Tools/ui-tokens.mjs from StreamingAssets/Content/ui/tokens.json. Do not edit. </auto-generated> */', ':root {'];
  for (const [group, spec] of Object.entries(tokens.groups)) {
    const values = tokens[group];
    if (!values || typeof values !== 'object') throw new Error(`ui-tokens: group "${group}" has no values`);
    for (const [key, value] of Object.entries(values)) {
      const css = typeof value === 'number' ? `${value}${spec.unit}` : String(value);
      lines.push(`    --${spec.prefix}-${kebab(key)}: ${css};`);
    }
  }
  lines.push('}', '');
  return lines.join('\n');
}

function walk(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

// Raw values a hand-written USS file may not contain. var(--…) references and comments are removed first.
export function lintUss(text) {
  const problems = [];
  const body = text.replace(/\/\*[\s\S]*?\*\//g, '');
  body.split('\n').forEach((raw, i) => {
    const decl = raw.match(/^\s*([-a-z]+)\s*:\s*(.+?);?\s*$/);
    if (!decl || raw.trim().startsWith('--')) return;
    const value = decl[2].replace(/var\(--[a-z0-9-]+\)/g, '');
    if (/#[0-9a-fA-F]{3,8}\b/.test(value) || /\brgba?\(/.test(value) || /\bhsla?\(/.test(value)) problems.push(`${i + 1}: raw colour in "${raw.trim()}"`);
    for (const m of value.matchAll(/(^|[^a-zA-Z0-9_-])(-?\d*\.?\d+)(px|%|ms|s|deg|em|rem|vw|vh)?(?![a-zA-Z0-9_-])/g)) {
      const [, , num, unit] = m;
      const n = Number(num);
      if (n === 0) continue;
      if (!unit && n === 1) continue;
      problems.push(`${i + 1}: raw number "${num}${unit || ''}" in "${raw.trim()}" (use a token variable)`);
    }
  });
  return problems;
}

const tokens = JSON.parse(readFileSync(TOKENS, 'utf8'));
const text = renderTokens(tokens);
const errors = [];
if (CHECK) {
  if (!existsSync(OUT) || readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n') !== text) errors.push(`${relative(ROOT, OUT)} is stale — run node Tools/ui-tokens.mjs`);
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, text);
}
const sheets = walk(UI).filter((f) => f.endsWith('.uss') && f !== OUT);
for (const f of sheets) for (const p of lintUss(readFileSync(f, 'utf8'))) errors.push(`${relative(ROOT, f).replace(/\\/g, '/')}:${p}`);
if (errors.length) { console.error(`ui-tokens: ${errors.length} problem(s)\n  ${errors.join('\n  ')}`); process.exit(1); }
console.log(`ui-tokens: ${CHECK ? 'check ok' : 'wrote Tokens.uss'} (${Object.keys(tokens.groups).length} groups, ${sheets.length} style sheets linted)`);
