#!/usr/bin/env node
// Writes Content/settings/webKeyMap.json: how a web-format config key (gameConfig.<bundle path>, settings.<key>) maps
// onto this build's content files (US-15.4, D-162). Derived from Tools/transform.config.json (each catalog table or
// object exported from bundle.<path>) plus Tools/export/legacy-key-map.json (renames and extra roots), so the importer
// in the game reads data, never a hand-kept list.
//
//   node Tools/web-key-map.mjs           write
//   node Tools/web-key-map.mjs --check   fail on drift
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'Unity', 'Assets', 'StreamingAssets', 'Content', 'settings', 'webKeyMap.json');
const config = JSON.parse(readFileSync(join(ROOT, 'Tools', 'transform.config.json'), 'utf8'));
const legacy = JSON.parse(readFileSync(join(ROOT, 'Tools', 'export', 'legacy-key-map.json'), 'utf8'));
const BUNDLE = 'bundle.';

const roots = [];
for (const t of config.tables) {
  if (!t.from.startsWith(BUNDLE)) continue;
  if (!Array.isArray(t.key) || t.key.length !== 1) continue; // composite-keyed tables have no single web path
  roots.push({ web: t.from.slice(BUNDLE.length), file: t.out, keyed: true });
}
for (const o of config.objects) {
  if (o.from === 'bundle' && Array.isArray(o.pick)) { for (const k of o.pick) roots.push({ web: k, file: o.out, path: k }); continue; }
  if (!o.from.startsWith(BUNDLE)) continue;
  roots.push({ web: o.from.slice(BUNDLE.length), file: o.out });
}
for (const r of legacy.extraRoots || []) roots.push({ web: r.web, file: r.file, path: r.path });
roots.sort((a, b) => b.web.split('.').length - a.web.split('.').length || (a.web < b.web ? -1 : a.web > b.web ? 1 : 0));

const doc = {
  comment: 'Generated by Tools/web-key-map.mjs (D-162): web config keys → content. A key is gameConfig.<web>.<rest> for the longest matching root (keyed: <rest> starts with the row id), or settings.<player setting>; settings.gameConfig.* mirrors gameConfig.* and is not imported twice. Renames apply first. Anything else is reported, never dropped.',
  gameConfigPrefix: 'gameConfig.',
  settingsPrefix: 'settings.',
  mirrorPrefix: 'settings.gameConfig.',
  renames: legacy.renames,
  roots,
};
const text = `${JSON.stringify(doc, null, 2)}\n`;
if (process.argv.includes('--check')) {
  const now = existsSync(OUT) ? readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n') : '';
  if (now !== text) { console.error('web-key-map: settings/webKeyMap.json is stale; run node Tools/web-key-map.mjs'); process.exit(1); }
  console.log(`web-key-map: check ok (${roots.length} roots)`);
} else {
  writeFileSync(OUT, text);
  console.log(`web-key-map: wrote ${roots.length} roots`);
}
